language: node_js
node_js:
  - "8"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project xiaoswaii-26b70 --token 1/Gfag-6Q2K6swqy2P3EKqcTh8lpWzXI1TrxWFIVcBAj5fSDMp1OnxQJG9zYM6jGkL