language: node_js
node_js:
  - "8"
install:
  - npm install -g firebase-tools
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/vv0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb 
script:
 - echo "Deploy!!"
 - hugo
after_success:
 - firebase deploy --project xiaoswaii-26b70 --token 1/Gfag-6Q2K6swqy2P3EKqcTh8lpWzXI1TrxWFIVcBAj5fSDMp1OnxQJG9zYM6jGkL